[workspace]
members = ["lib", "bin"]
resolver = "2"

# Common metadata for all workspace crates
[workspace.package]
name = "genpass"
version = "1.0.1"
authors = ["Abdogouhmad <gouhmada@gmail.com>"]
edition = "2021"
description = "Password & username generator with notes saved in a file"
license = "MIT"
repository = "https://github.com/Abdogouhmad/genpass"
keywords = ["rust", "password", "username", "generator", "cli", "tools"]
categories = ["command-line-utilities", "web-programming", "cryptography"]
readme = "README.md"
homepage = "https://github.com/Abdogouhmad/genpass"
documentation = "https://docs.rs/genpass"

# ===========================
# Profiles
# ===========================
[profile.dev]
opt-level = 0
debug = true
overflow-checks = true
incremental = true

[profile.release]
opt-level = "z"   # Optimize for size
lto = true        # Link time optimization
codegen-units = 1
panic = "abort"   # Small binary size
strip = true      # Strip symbols to reduce size

# ===========================
# Workspace-wide dependencies
# ===========================
[workspace.dependencies]
clap = { version = "4.3", features = ["derive"] }  # CLI argument parser
serde = { version = "1.0", features = ["derive"] } # For saving notes in JSON
serde_json = "1.0"                                 # JSON storage
rand = "0.9.2"                                     # Random password generation
anyhow = "1.0"                                     # Error handling
log = "0.4"                                        # Logging
env_logger = "0.11.8"                              # Logging backend
aes-gcm = "0.10"
argon2 = { version = "0.5.3", features = ["std"] }
rpassword = "7.4.0"
zeroize = "1.8.2"
# ===========================
# Optional features
# ===========================
[workspace.features]
# # Enable optional password rules (length, symbols, etc.)
# password_rules = []

# Enable logging
logging = ["log", "env_logger"]
